### ISSUE TITLE
[STE-23] Opzetten van Amir als collaborator in Vue.js-project met Primic.io

### ISSUE THREAD

**Issue by M4TThys123** [M4TThys123/Steeds-Voorwaarts#10]
### Doel:

Het doel van deze issue is om een mede frontend developer op te zetten in het bestaande Vue.js-project met [Prismic.io](http://Prismic.io) als content management systeem. Dit zal de nieuwe developer helpen om snel aan de slag te gaan met de codebase en de ontwikkelingsworkflow te begrijpen.

### To-do:

- [X] **Repo Setup:**
  - [X] Repository clonen.
  - [X] Repo accepteren
  - [X] Afhankelijkheden installeren met `npm install`.
- [X] **Prismic Configuratie:**
  - [X] Inloggen op primic.
- [x] **Vue-cli:**
  - [x] Vue-cli installeren.
- [ ] **Vue-router:**
  - [ ] Router-configuratie bekijken.
  - [ ] Navigatie tussen pagina's begrijpen.
- [ ] **Styling:**
  - [ ] Stijlconventies begrijpen.
- [ ] **Componentenstructuur:**
  - [ ] Structuur van componenten begrijpen.
  - [ ] Kennis nemen van veelvoorkomende componenten.
- [ ] **Coding Conventies:**
  - [ ] Bekend zijn met gebruikte coding conventies.
- [ ] **Documentatie:**
  - [ ] Documentatie lezen.
  - Notion:
- [ ] **Lokale Ontwikkeling:**
  - [ ] Lokale ontwikkelingsserver starten (`npm run serve`).
  - [ ] Ontwikkelingsworkflow begrijpen.
- [ ] **Versiebeheer:**
  - [ ] Git omgeving bekijken in GitHub Desktop.
  - [ ] Eigen branche beheren maken.
  - [ ] Changes indienen (commit & push).

<sub>From [SyncLinear.com](https://synclinear.com) | [STE-23](https://linear.app/steeds-voorwaarts/issue/STE-23/opzetten-van-amir-als-collaborator-in-vuejs-project-met-primicio)</sub>
